# -*- coding: utf-8 -*-
"""
策略模块初始化
"""
from .strategy import (
    BaseAStockStrategy,
    MacdKdjStrategy,
    RsiStrategy,
    BollingerStrategy,
    MaCrossStrategy,
    KdjOversoldStrategy,
    MacdZeroAxisStrategy,
    TripleScreenStrategy,
    TurtleTradingStrategy,
    MomentumStrategy,
    MeanReversionStrategy,
    DonchianStrategy,
    WilliamsRStrategy,
    CCIStrategy,
    EMACrossStrategy,
    VolumeSpreadStrategy,
    SARStrategy,
    KeltnerChannelStrategy,
    # 优化策略
    EmaRsiStrategy,
    DualMacdStrategy,
    MacdStrategy,
    BollRsiStrategy,
    TurtleBreakoutStrategy,
    TripleEmaTrendStrategy,
    KdjMacdResonanceStrategy,
    RsiAtrAdaptiveStrategy,
    MacdBollStrategy,
    KdjRsiStrategy,
    MaVolumeStrategy,
    AtrStopStrategy,
    CompositeStrategy,
    MacdKdjFibonacciStrategy,
    BollRsiOptimizedStrategy,
    KdjRsiOptimizedStrategy,
    # 别名
    MacdStrategyWithATR,
    RsiStrategyWithTrendFilter,
    TurtleStrategyWithFilter,
    MacdWithAtr,
    RsiWithTrend,
    TurtleWithFilter,
    # 工厂函数
    get_strategy_class,
    get_all_strategy_types,
    get_basic_strategy_types,
    get_optimized_strategy_types,
    create_strategy_with_config,
)
from .portfolio import (
    PortfolioStrategy,
    StrategyConfig,
    create_balanced_portfolio,
    create_aggressive_portfolio,
    create_conservative_portfolio,
)
from .market_state import (
    MarketStateDetector,
    StrategyRotator,
)
from .param_space import (
    PARAM_SPACES,
    get_param_space,
    get_all_strategy_types,
    get_all_param_spaces,
)

__all__ = [
    # 策略类 (36个策略 + 基类)
    'BaseAStockStrategy',
    'MacdKdjStrategy',
    'RsiStrategy',
    'BollingerStrategy',
    'MaCrossStrategy',
    'KdjOversoldStrategy',
    'MacdZeroAxisStrategy',
    'TripleScreenStrategy',
    'TurtleTradingStrategy',
    'MomentumStrategy',
    'MeanReversionStrategy',
    'DonchianStrategy',
    'WilliamsRStrategy',
    'CCIStrategy',
    'EMACrossStrategy',
    'VolumeSpreadStrategy',
    'SARStrategy',
    'KeltnerChannelStrategy',
    # 优化策略类
    'EmaRsiStrategy',
    'DualMacdStrategy',
    'MacdStrategy',
    'BollRsiStrategy',
    'TurtleBreakoutStrategy',
    'TripleEmaTrendStrategy',
    'KdjMacdResonanceStrategy',
    'RsiAtrAdaptiveStrategy',
    'MacdBollStrategy',
    'KdjRsiStrategy',
    'MaVolumeStrategy',
    'AtrStopStrategy',
    'CompositeStrategy',
    'MacdKdjFibonacciStrategy',
    'BollRsiOptimizedStrategy',
    'KdjRsiOptimizedStrategy',
    # 别名
    'MacdStrategyWithATR',
    'RsiStrategyWithTrendFilter',
    'TurtleStrategyWithFilter',
    'MacdWithAtr',
    'RsiWithTrend',
    'TurtleWithFilter',
    # 工厂函数
    'get_strategy_class',
    'get_all_strategy_types',
    'get_basic_strategy_types',
    'get_optimized_strategy_types',
    'create_strategy_with_config',
    # 组合策略
    'PortfolioStrategy',
    'StrategyConfig',
    'create_balanced_portfolio',
    'create_aggressive_portfolio',
    'create_conservative_portfolio',
    # 市场状态
    'MarketStateDetector',
    'StrategyRotator',
    # 参数空间 (统一，不区分基础和优化)
    'PARAM_SPACES',
    'get_param_space',
    'get_all_strategy_types',
    'get_all_param_spaces',
]
